---
- name: Ensure required packages exists
  apt:
    name: jq
    state: present

- name: Check if vault has been initialized
  shell: vault status --format=json | jq .initialized
  register: init_result

- name: Initialize Vault
  shell: |
    vault operator init -key-shares=5 -key-threshold=3 -format=json > {{ backup_dir }}/{{ init_file }}
    jq -r '.unseal_keys_b64[]' {{ backup_dir }}/{{ init_file }} > {{ backup_dir }}/{{ unseal_keys_file }}
    jq -r '.root_token' {{ backup_dir }}/{{ init_file }} > {{ backup_dir }}/{{ root_token_file }}
    chmod 600 {{ backup_dir }}/{{ init_file }}
    chmod 600 {{ backup_dir }}/{{ unseal_keys_file }}
    chmod 600 {{ backup_dir }}/{{ root_token_file }}
  args:
    executable: /bin/bash
  when:
    - not (init_result.stdout | bool)

