---
- name: Vault setup
  block:
    # Preparation
    - import_tasks: share/setup.yml

    # Installation
    - import_tasks: vault/install.yml
    - import_tasks: vault/config.yml
    - import_tasks: vault/service.yml
    - import_tasks: vault/init.yml
    - import_tasks: vault/unseal.yml
    - import_tasks: vault/read_data.yml

    # Configuration
    - import_tasks: approle/init.yml
      environment:
        VAULT_TOKEN: "{{ vault_root_token }}"
    - import_tasks: approle/store_data.yml
      environment:
        VAULT_TOKEN: "{{ vault_root_token }}"
    - import_tasks: approle/setup_policy.yml
      environment:
        VAULT_TOKEN: "{{ vault_root_token }}"
    - import_tasks: approle/login.yml

    # Setup restore script
    - import_tasks: scripts/restore.yml
      environment:
        VAULT_TOKEN: "{{ vault_root_token }}"

    # Setup backup job
    - import_tasks: backup/cron.yml
  environment:
    VAULT_ADDR: "http://{{ vault_ip }}:8200"
