diun_container_name: diun
diun_image: crazymax/diun:4.29
diun_data_path: "{{ app_data_mount_path }}/{{ ansible_hostname }}/diun/data"
diun_env:
  - "TZ=Europe/Stockholm"
  - "DIUN_WATCH_WORKERS=20"
  - "DIUN_WATCH_SCHEDULE=0 */6 * * *"
  - "DIUN_WATCH_JITTER=30s"
  - "DIUN_PROVIDERS_DOCKER=true"
  - "DIUN_NOTIF_GOTIFY_ENDPOINT=http://192.168.50.69:8080"
  - "DIUN_NOTIF_GOTIFY_TOKEN=A6Sr9CQTqpx7r-W"


